### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by mprabhakarece** [CartoType/CartoType-Public-7-0#1]
hi.
 
   i build code using  visual studio ,i got error like

fatal error LNK1104: cannot open file '..\..\..\..\bin\14.0\x64\Debug\cartotype.lib'

please suggest the issue

thanks
prabha

**Comment by GrahamAsher** [comment]
You need a copy of cartotype.lib. You can get it from [one of the SDKs available for download ](https://www.cartotype.com/developers/evaluation-sdks)at the CartoType web site. I assume you're trying to build the Windows demo, so you need the Windows SDK.
